
export const FETCH_CITY ="FETCH_CITY"
export const DELETE_CITY ="DELETE_CITY"
export const ADD_FAVORITE_CITY = "ADD_FAVORITE_CITY"
export const FETCH_FAVORITE_CITY = "FETCH_FAVORITE_CITY"
export const GET_WEATHER_LIST = "GET_WEATHER_LIST"
