
export const FETCH_CITY ="FETCH_CITY"
export const SET_FAVORITE_CITY = "SET_FAVORITE_CITY"
export const GET_WEATHER_DETAIL = "GET_WEATHER_DETAIL"
export const GET_LIST_WEATHER = "GET_LIST_WEATHER"
export const ADD_FAVORIS = "ADD_FAVORIS"

